### ISSUE TITLE
troubles during install 

### ISSUE THREAD

**Issue by javarminator** [ceph/calamari-clients#84]
Dear all, 
I've got some troubles with the installation process. 

When I run make dist,the result is just a tar of the repository (weird, isn't it ? espacially knowing that the operation lasts about 7 minutes) and when I run make dist I git this error stack 

Running "concurrent:dist" (concurrent) task
[D] Task source: /tmp/calamari_client_repo/calamari-clients/manage/node_modules/grunt-concurrent/tasks/concurrent.js
    
    Running "copy:styles" (copy) task
    [D] Task source: /tmp/calamari_client_repo/calamari-clients/manage/node_modules/grunt-contrib-copy/tasks/copy.js
    
    
    Done, without errors.
    
    
    Execution Time (2015-01-21 13:17:54 UTC)
    loading tasks   4ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 27%
    copy:styles    10ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 67%
    Total 15ms
        Warning: 
    /tmp/calamari_client_repo/calamari-clients/manage/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
      throw err;
            ^
    Error: ENOENT, no such file or directory 'dist/images/logo.png'
        at Object.fs.statSync (fs.js:695:18)
        at processed (/tmp/calamari_client_repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:84:43)
        at /tmp/calamari_client_repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:131:29
        at callDone (/tmp/calamari_client_repo/calamari-clients/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:5)
        at ChildProcess.<anonymous> (/tmp/calamari_client_repo/calamari-clients/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:198:5)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:756:16)
        at Socket.<anonymous> (child_process.js:969:11)
        at Socket.emit (events.js:95:17)
        at Pipe.close (net.js:465:12) Use --force to continue.
        
        Aborted due to warnings.
    

Can anyone help me please ? 

details : I'am building the packages on a centos 7 Virtual Machine .

Regards 
F

**Comment by kmkanagaraj** [comment]
It takes time because it needs to download the node modules specified in package.json.  Do you see the tarball getting generated or it failed in the process?

**Comment by javarminator** [comment]
Hi, 
Thank ou for your answer, I don't stop the building process when I use make dist, a tarball is generated, and it contains the intial repository  compressed

**Comment by kmkanagaraj** [comment]
Here the steps to build in Fedora, it should hold good for CentOS as well https://github.com/ceph/calamari-clients/wiki/Fedora-Build-Instructions

Have you tried this?

You could use vagrant if you want to build the rpm. Please refer http://ceph.com/calamari/docs/development/building_packages.html#calamari-clients

**Comment by javarminator** [comment]
Well that's the point, when I use make build-real as referred in the first link, I got the error stack I copied in my first post (and I have followed all the steps) 

thank you for your patience :)

**Comment by joehandzik** [comment]
I ran into this problem, lemme backtrack when I get into the office to see what I did to fix it. One thing that I tweaked was switching to building as a user via sudo instead of building directly as root. Are you building as root or using sudo?

Joe



On Jan 21, 2015, at 8:21 AM, javarminator <notifications@github.com<mailto:notifications@github.com>> wrote:


Well that's the point, when I use make build-real as referred in the first link, I got the error stack I copied in my first post (and I have followed all the steps)

thank you for your patience :)

**Comment by javarminator** [comment]
Thank you for your answer 

I tried to use sudo but a new error came out 
-*
 Warning: Running "compass:dist" (compass) task
    Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.
-*

I'am certain that ruby and compass are correctly installed 

F

**Comment by joehandzik** [comment]
Ha! Yup, you're right where I was. You need to change your secure_path EV in the sudo file (I think /etc/sudoers). The problem is that ruby gems end up in a directory that the secure path drops. You can change secure path to your user account's PATH value, or use sudo -i to bring your user's path with when using sudo, instead of using the secure path. You may run into another error or two from here on, I forget.

Joe



On Jan 21, 2015, at 9:01 AM, javarminator <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your answer

I tried to use sudo but a new error came out
-*
Warning: Running "compass:dist" (compass) task
Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.
-*

I'am certain that ruby and compass are correctly installed

F

**Comment by kmkanagaraj** [comment]
@javarminator can you check if they are in your PATH? 

I remember having same kind of issue long back and re-installing them worked.

**Comment by javarminator** [comment]
@kmkanagaraj 
The use of sudo reset the PATH, so I edited the root PATH and exported it as a normal user, it seems that the problem is solved 
I am now dealing with bower troubles (I have a proxy on my station )
cheers

**Comment by joehandzik** [comment]
Yuck, you're at the same place I'm at now. I'll update when I have a chance to try out what the red hat team suggested for debugging.

Joe



On Jan 21, 2015, at 10:07 AM, javarminator <notifications@github.com<mailto:notifications@github.com>> wrote:


@kmkanagaraj<https://github.com/kmkanagaraj>
The use of sudo reset the PATH, so I edited the root PATH and exported it as a normal user, it seems that the problem is solved
I am now dealing with bower troubles (I have a proxy on my station )
cheers

**Comment by ZhangZhenhua** [comment]
Hi @javarminator @kmkanagaraj @joehandzik ,

I am running into the same issue on Centos7 now.  It ends up with same error using both root and sudo. In the sudo case, I changed the secure_path to avoid PATH problem but still met exact error in the first post of this issue. Could you please shed some light on it? Thank you very much!

```
/root/git/calamari-clients/manage/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
      throw err;
            ^
    Error: ENOENT, no such file or directory 'dist/images/logo.png'
        at Object.fs.statSync (fs.js:696:18)
        at processed (/root/git/calamari-clients/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:84:43)
        at /root/git/calamari-clients/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:131:29
        at callDone (/root/git/calamari-clients/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:5)
        at ChildProcess.<anonymous> (/root/git/calamari-clients/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:198:5)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:766:16)
        at Socket.<anonymous> (child_process.js:979:11)
        at Socket.emit (events.js:95:17)
        at Pipe.close (net.js:466:12) Use --force to continue.

        Aborted due to warnings.

```

**Comment by ChristinaMeno** [comment]
@ZhangZhenhua Would you please share what steps you are taking to get here?

**Comment by ZhangZhenhua** [comment]
@GregMeno Sure, thanks for your responding!

Here is my basic env:

```
[root@zhenhua-calamari-2 calamari-clients]# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 
[root@zhenhua-calamari-2 calamari-clients]# uname -a
Linux zhenhua-calamari-2.novalocal 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

And below is the process I follow when I build calamari-clients(newly cloned, so using latest master.).

```
１．　# yum install npm ruby rubygems ruby-devel
２．　# npm install -g grunt grunt-cli bower grunt-contrib-compass
３．　# gem update --system && gem install compass
４．　# cd calamari-clients
５．　# make build-real
６．　# make dist
７．　#rpmbuild ...
```

Actually, during my first installation, I successfully made it to step 6 and failed on step 7, sorry I didn't save the error message for it. And all following installations failed at step 5 with message below:

```
Running "concurrent:dist" (concurrent) task
>> Warning: There are more tasks than your concurrency limit. After this limit
>> is reached no further tasks will be run until the current tasks are
>> completed. You can adjust the limit in the concurrent task options

    Loading "connect_proxy.js" tasks...ERROR
    >> TypeError: Cannot read property 'prototype' of undefined

    Running "copy:styles" (copy) task


    Done, without errors.


    Execution Time (2015-09-21 01:37:03 UTC)
    loading tasks   7ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 39%
    copy:styles    11ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 61%
    Total 18ms
        Warning: 
    /root/git/calamari-clients/manage/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
      throw err;
            ^
    Error: ENOENT, no such file or directory 'dist/images/logo.png'
        at Object.fs.statSync (fs.js:696:18)
        at processed (/root/git/calamari-clients/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:84:43)
        at /root/git/calamari-clients/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:131:29
        at callDone (/root/git/calamari-clients/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:5)
        at ChildProcess.<anonymous> (/root/git/calamari-clients/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:198:5)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:766:16)
        at Socket.<anonymous> (child_process.js:979:11)
        at Socket.emit (events.js:95:17)
        at Pipe.close (net.js:466:12) Use --force to continue.

        Aborted due to warnings.


Execution Time (2015-09-21 01:37:01 UTC)
git-describe:git.js  58ms  ▇▇▇ 2%
concurrent:dist      3.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 97%
Total 3.5s
make[1]: *** [build-stamp] Error 6
make[1]: Leaving directory `/root/git/calamari-clients/manage'
make: *** [build-ui] Error 2

```

Currently I am using a officially build RPM to workaround this issue. But it would be great if I can build the RPM myself. So any suggestions? Or could you please share your steps to build rpm thus I can try in my env? Thanks a lot!

**Comment by kivis-online** [comment]
I have the same problem：

   CentOS 7.2 x86_64

   not root user

   $ sudo env PATH=$PATH make build-real

```
    Warning:
/home/ceph/romana/manage/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
  throw err;
        ^
Error: ENOENT, no such file or directory 'dist/images/logo.png'
    at Object.fs.statSync (fs.js:696:18)
    at processed (/home/ceph/romana/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:84:43)
    at /home/ceph/romana/manage/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:131:29
    at callDone (/home/ceph/romana/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:5)
    at ChildProcess.<anonymous> (/home/ceph/romana/manage/node_modules/grunt/node_modules/grunt-legacy-util/index.js:198:5)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12) Use --force to continue.

    Aborted due to warnings.
```

**Comment by zphj1987** [comment]
@kivis-online @javarminator 
i know this problem , it is the version of grunt-contrib-compass's problem，because the 0.5 have a bug,so you can change the package.json,and everything will ok

cd romana
change  grunt-contrib-imagemin version to 0.4.1

``` bash
[root@calamarimake romana]# grep "grunt-contrib-imagemin" -R *
admin/package.json: "grunt-contrib-imagemin": "~0.1.4",
dashboard/package.json: "grunt-contrib-imagemin": "0.1.4",
login/package.json: "grunt-contrib-imagemin": "~0.1.3",
manage/package.json: "grunt-contrib-imagemin": "~0.3.0",
```

change to ：

``` bash
admin/package.json: "grunt-contrib-imagemin": "0.4.1",
dashboard/package.json: "grunt-contrib-imagemin": "0.1.4",
login/package.json: "grunt-contrib-imagemin": "0.4.1",
manage/package.json: "grunt-contrib-imagemin": "0.4.1",
```

and continue···
